# Generated by Django 6.1.1 on 2026-10-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_customizable',
            field=models.BooleanField(default=False),
        ),
    ]
